# This is a basic workflow to help you get started with Actions

name: armtemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
 
  armDeploy:

    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v4

      
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group rg-githubactions
        uses: Azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionId: 810f2833-d0a2-4c1d-94de-e2953af70a05
          region: Australia East
          template: .github/workflows/resourcegroup.json
          deploymentName: rg-githubactions

      - name: Deploy storage account
        uses: Azure/arm-deploy@v2
        with:
            scope: resourcegroup
            resourceGroupName: rg-githubactions
            subscriptionId: 810f2833-d0a2-4c1d-94de-e2953af70a05
            template: .github/workflows/storageaccount.json
            parameters: .github/workflows/storageaccount.parameters.json
            deploymentMode: incremental
